### PR TITLE
Add apple silicon binaries

### PR DESCRIPTION
**Pull request by n2o**
Adds apple silicon binaries of ffmpeg, ffprobe and whisper.cpp

### CODE REVIEW

**Comment by bits-by-brandon** [comment]
Thanks! I'll take a look soon

**Review by bits-by-brandon — APPROVED** [review]

**Comment by jeffrafter** [comment]
@n20: what was your compilation process? Just curious if this is something we could move into a github action?

**Comment by n2o** [comment]
n20 is a different user ;-)

I just tried this repository to get into whisper in a tauri application. Adding the binaries was necessary to be able to call `yarn tauri dev` for the typical development process.

But in my project I integrated https://github.com/tazz4843/whisper-rs. So you don't need a binary and can use it directly in Rust.

**Comment by jeffrafter** [comment]
Ah! @n2o! Sorry about that. My question was really around how you compiled for all of the architectures. I haven't found a good example that has no dependencies (like your binaries).

**Pull request merged**
